const fs=require('fs'),path=require('path'),http=require('http'),os=require('os'),{spawn}=require('child_process'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),pdv=path.resolve(repo,'../flowpdv-sistema/adega-pdv-gestao');
const out=path.join(repo,'.impeccable/review');fs.mkdirSync(out,{recursive:true});
if(process.env.DESIGN_BROWSER){
 const {app,BrowserWindow}=require('electron');
 app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{contextIsolation:true,backgroundThrottling:false,offscreen:true}}),errors=[];win.webContents.on('console-message',(_,level,msg)=>{if(level===3&&!msg.includes('favicon'))errors.push(msg)});
 const js=s=>win.webContents.executeJavaScript(s),wait=async s=>{for(let i=0;i<140;i++){if(await js(s))return;await new Promise(r=>setTimeout(r,50));}throw Error('Espera: '+s);};
 const shot=async(name,width)=>{win.setContentSize(width,1000);await js('window.scrollTo(0,0);document.fonts.ready');await js('document.getAnimations().forEach(a=>a.finish())');await new Promise(r=>setTimeout(r,450));win.webContents.invalidate();await new Promise(r=>setTimeout(r,100));assert.equal(await js('document.documentElement.scrollWidth<=innerWidth'),true,'overflow '+name);fs.writeFileSync(path.join(out,name+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());};
 try{
 if(process.env.TEST_GESTAO_UI){
 await win.loadURL(process.env.DESIGN_BROWSER+'/gestao');await wait("document.querySelectorAll('.prod-card').length===6");
 await js("document.querySelector('[data-del-foto]').click()");await wait("document.querySelector('[data-add-foto]').textContent.includes('Adicionar foto')");
 assert.equal(await js("document.querySelector('.prod-card').querySelector('[data-del-foto]')"),null);
 for(const width of [1440,390]){win.setContentSize(width,800);await js("window.scrollTo(0,500);document.querySelector('[data-aba=loja]').click()");assert.equal(await js('scrollY'),0);assert.equal(await js("document.querySelector('#lj-end').placeholder"),'Informe o endereço comercial');await js("window.scrollTo(0,500);document.querySelector('[data-aba=cardapio]').click()");assert.equal(await js('scrollY'),0);await shot('gestao-fotos-'+width,width);}
 console.log('GESTAO PASS: fotos explícitas, remoção simulada, abas no topo e placeholders genéricos.');app.exit(0);return;}
 if(process.env.TEST_SCROLL){await require('./scroll-categorias.cjs')({js,wait,win,url:process.env.DESIGN_BROWSER});app.exit(0);return;}
 await win.loadURL(process.env.DESIGN_BROWSER+'/gestao');await wait("document.querySelectorAll('.prod-card').length===6");
 for(const aba of ['cardapio','loja','pedidos','qr']){await js(`document.querySelector('[data-aba="${aba}"]').click()`);if(aba==='qr')await wait("!!document.querySelector('#qr-loja-art img')");for(const width of [1440,390])await shot('gestao-'+aba+'-'+width,width);}
 await win.loadURL(process.env.DESIGN_BROWSER+'/cliente');await wait("!!document.querySelector('.menu-item')");for(const width of [1440,768,390])await shot('cliente-'+width,width);
 await js("document.querySelector('.menu-item').click()");await wait("!!document.querySelector('#prod-overlay')");await shot('produto-390',390);await shot('produto-1440',1440);win.setContentSize(390,1000);
 await js("document.querySelector('#btn-add').click()");await wait("!!document.querySelector('#btn-ver-pedido') && !document.querySelector('#prod-overlay')");await js("document.querySelector('#btn-ver-pedido').click()");await wait("!!document.querySelector('#sheet')");await wait("!document.querySelector('.app-toast')");await shot('carrinho-390',390);
 assert.match(await js("document.querySelector('.cart-total').textContent"),/29,90/);
 await win.loadURL(process.env.DESIGN_BROWSER+'/v2/demonstracao');await wait("document.querySelectorAll('.v2-product').length===6");for(const width of [1440,390])await shot('v2-'+width,width);
 await js("document.querySelector('.v2-customize').open=true;document.querySelector('.v2-product button').click()");await wait("document.querySelectorAll('aside article').length===1");
 assert.equal(errors.filter(e=>!e.includes('net::ERR')).length,0,errors.join('\n'));
 console.log('DESIGN PASS: sem overflow 390/768/1440; produto, carrinho e V2 aprovados.');app.exit(0);
 }catch(e){console.error(e);app.exit(1);}});
}else{(async()=>{
 const esbuild=require(path.join(pdv,'node_modules/esbuild'));
 const photos=fs.readdirSync(path.join(repo,'fotos-teste')).filter(n=>/\.jpg$/i.test(n));const burger='download (1).jpg',juice=photos.find(n=>n.startsWith('Orange')),pizza=photos.find(n=>n.startsWith('pizza')),cola=photos.find(n=>n.startsWith('Coca'));
 const photoFiles=[burger,juice,pizza,cola].map(n=>path.join(repo,'fotos-teste',n));
 const products=[{id:'1',nome:'Burger da casa',categoria:'Hambúrgueres',preco:29.9,descricao:'Pão brioche, carne grelhada, queijo e bacon crocante.',fotoUrl:'/demo-photo/0',destaque:true},{id:'2',nome:'Suco de laranja',categoria:'Bebidas',preco:9.5,descricao:'Laranja espremida na hora. Copo de 400 ml.',fotoUrl:'/demo-photo/1'},{id:'3',nome:'Pizza da casa',categoria:'Pizzas',preco:49.9,descricao:'Massa artesanal, queijo e ingredientes da casa.',fotoUrl:'/demo-photo/2',destaque:true},{id:'4',nome:'Coca-Cola',categoria:'Bebidas',preco:7,descricao:'Bem gelada para acompanhar seu pedido.',fotoUrl:'/demo-photo/3'},{id:'5',nome:'Burger com queijo',categoria:'Hambúrgueres',preco:24.9,descricao:'Carne grelhada, queijo derretido e molho da casa.',fotoUrl:'/demo-photo/0'},{id:'6',nome:'Pizza individual',categoria:'Pizzas',preco:27.9,descricao:'A pizza da casa em tamanho individual.',fotoUrl:'/demo-photo/2'}];
 const fixture={produtos:products,overlays:Object.fromEntries(products.map(p=>[p.id,{...p,visivel:true}])),config:{horarioTexto:'Ter a Dom · 18:00–23:00',entregaTexto:'30–45 min',whatsapp:'',endereco:'',pausado:false},pedidos:[{id:'PED-10001',tipo:'mesa',numeroMesa:12,status:'novo',total:29.9,itens:[{nome:'Burger da casa',quantidade:1,preco:29.9,fotoUrl:'/demo-photo/0'}]},{id:'PED-10002',tipo:'loja',status:'em_preparo',total:9.5,itens:[{nome:'Suco de laranja',quantidade:1,preco:9.5,fotoUrl:'/demo-photo/1'}]}]};
 const mock={
 'auth.js':`export const nomeDaLoja=l=>l.nome;export const sairDaLoja=async()=>{};`,
 'backup.js':`export const carregarBackupLoja=async()=>({produtos:fixture.produtos});export const precoProduto=p=>p.preco;export const produtoAtivo=()=>true;`,
 'overlay.js':`export const listarOverlays=async()=>structuredClone(fixture.overlays);export const lerConfig=async()=>structuredClone(fixture.config);export const salvarOverlay=async(c,id,p)=>{fixture.overlays[id]={...fixture.overlays[id],...p}};export const salvarConfig=async(c,p)=>{fixture.config={...fixture.config,...p}};export const publicarCardapio=async()=>{throw Error('Demonstração: nada é publicado.')};export const assinarUpload=async()=>{throw Error('Demonstração: upload desabilitado.')};export const enviarFotoCloudinary=async()=>{};export const removerFoto=async()=>{throw Error('Demonstração: remoção desabilitada.')};`,
 'pedidos.js':`export const escutarPedidosLoja=(c,data)=>{const fn=()=>data(structuredClone(fixture.pedidos));fixture.emit=fn;queueMicrotask(fn);return()=>{}};export const atualizarStatusPedido=async(c,id,st)=>{fixture.pedidos.find(p=>p.id===id).status=st;fixture.emit()};export const invalidarCardapioPublico=()=>{};export const lerCardapioPublico=async()=>({nome:'Casa do Sabor',...fixture.config,produtos:fixture.produtos});export const criarPedido=async()=>{throw Error('Demonstração: nenhum pedido é enviado.')};`,
 'v2.js':`export const catalogoV2=async()=>({nome:'Casa do Sabor',publicado:true,versao:1,canais:{retirada:true,delivery:true},produtos:fixture.produtos.map(p=>({...p,ativo:true,precoCentavos:Math.round(p.preco*100),grupos:[]}))});export const enviarV2=async()=>{throw Error('Demonstração: nenhum pedido é enviado.')};export const acompanharV2=async()=>{};export const cotarV2=async()=>{throw Error('Demonstração: cotação desabilitada.')};`
 };
 const built=await esbuild.build({stdin:{contents:`import './src/styles.css';import {renderPainel} from './src/pages/painel.js';import {renderCardapio} from './src/pages/cardapio.js';import {renderCardapioV2} from './src/pages/cardapio-v2.js';window.fixture=${JSON.stringify(fixture)};if(location.pathname==='/gestao')await renderPainel(document.querySelector('#app'),{chave:'LOJA-DEMO',licenca:{nome:'Casa do Sabor'}});else if(location.pathname.startsWith('/v2/'))await renderCardapioV2(document.querySelector('#app'));else await renderCardapio(document.querySelector('#app'),{chave:'LOJA-DEMO',mesa:12});`,resolveDir:repo},bundle:true,format:'esm',outfile:path.join(os.tmpdir(),'flow-design.js'),write:false,plugins:[{name:'demo',setup(b){b.onResolve({filter:/\/lib\/(auth|backup|overlay|pedidos|v2)\.js$/},a=>({path:path.basename(a.path),namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:mock[a.path]}));}}]});
 const js=built.outputFiles.find(f=>f.path.endsWith('.js')).text,css=built.outputFiles.find(f=>f.path.endsWith('.css')).text;
 const server=http.createServer((req,res)=>{if(req.url==='/app.js'){res.setHeader('Content-Type','text/javascript');res.end(js);}else if(req.url==='/app.css'){res.setHeader('Content-Type','text/css');res.end(css);}else if(req.url.startsWith('/demo-photo/')){const f=photoFiles[Number(req.url.split('/').pop())];if(f){res.setHeader('Content-Type','image/jpeg');res.end(fs.readFileSync(f));}else{res.statusCode=404;res.end();}}else if(req.url.startsWith('/logos/')){const f=path.join(repo,'public',req.url);if(fs.existsSync(f))res.end(fs.readFileSync(f));else{res.statusCode=404;res.end();}}else{res.setHeader('Content-Type','text/html;charset=utf-8');res.end('<!doctype html><html lang="pt-BR"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/app.css"><title>FlowPDV · demonstração local</title><div id="app"></div><span style="position:fixed;bottom:4px;right:8px;font:10px system-ui;color:#5b6573;z-index:100;background:#fff;padding:2px 6px;border-radius:4px;pointer-events:none">Demonstração · dados fictícios</span><script type="module" src="/app.js"></script></html>');}});
 await new Promise(r=>server.listen(Number(process.env.DESIGN_PORT)||0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 if(process.env.DESIGN_PREVIEW){console.log('PREVIEW '+url);return;}
 const env={...process.env,DESIGN_BROWSER:url};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(require(path.join(pdv,'node_modules/electron')),[__filename],{stdio:'inherit',env});child.on('exit',c=>{server.close();process.exitCode=c;});
})().catch(e=>{console.error(e);process.exitCode=1});}
