// Real Firebase emulators + rendered browser. No production access.
const path = require('node:path'), fs = require('node:fs'), assert = require('node:assert/strict');
const pdv = path.resolve(__dirname, '../../flowpdv-sistema/adega-pdv-gestao');
if (!process.env.GESTAO_BROWSER) {
  const { spawnSync } = require('node:child_process');
  const env = { ...process.env, GESTAO_BROWSER: '1' }; delete env.ELECTRON_RUN_AS_NODE;
  const result = spawnSync(require(path.join(pdv, 'node_modules/electron')), [__filename], {
    stdio: 'inherit', env, timeout: 120000
  });
  if (result.error) throw result.error;
  process.exit(result.status ?? 1);
}
const { app, BrowserWindow } = require('electron');
app.setPath('userData', fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'flowpdv-gestao-')));
process.env.FIRESTORE_EMULATOR_HOST = '127.0.0.1:8080';
process.env.FIREBASE_AUTH_EMULATOR_HOST = '127.0.0.1:9099';
const admin = require(path.join(pdv, 'functions/node_modules/firebase-admin'));
admin.initializeApp({ projectId: 'demo-flowpdv' });
const db = admin.firestore(), id = 'gestao-web-' + Date.now(), email = id + '@example.test', password = 'TesteLocal123!';
const out = path.resolve(__dirname, '../.impeccable/review');
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 1440, height: 1000, webPreferences: { offscreen: true, backgroundThrottling: false, contextIsolation: true } });
  // The harness deliberately reloads between cases; real browser users retain the guard.
  win.webContents.on('will-prevent-unload', event => event.preventDefault());
  const js = source => win.webContents.executeJavaScript(source);
  const wait = async source => { for (let i = 0; i < 300; i++) { if (await js(source)) return; await new Promise(r => setTimeout(r, 100)); } throw Error('Timeout: ' + source); };
  const submit = selector => js(`document.querySelector(${JSON.stringify(selector)}).requestSubmit()`);
  const fill = (selector, value) => js(`document.querySelector(${JSON.stringify(selector)}).value=${JSON.stringify(value)};document.querySelector(${JSON.stringify(selector)}).dispatchEvent(new Event('input',{bubbles:true}))`);
  const shot = async (width, focus = false) => {
    win.setContentSize(width, 1000); await js('window.scrollTo(0,0);document.fonts.ready');
    if (focus) await js('document.querySelector(".g-schedule").scrollIntoView()');
    await new Promise(r => setTimeout(r, 400)); win.webContents.invalidate();
    assert.equal(await js('document.documentElement.scrollWidth<=innerWidth'), true);
    fs.mkdirSync(out, { recursive: true }); fs.writeFileSync(path.join(out, `gestao-v2-${focus ? 'horarios-' : ''}${width}.png`), (await win.webContents.capturePage()).toPNG());
  };
  let user;
  try {
    user = await admin.auth().createUser({ email, password, emailVerified: true });
    const shop = db.doc(`lojas_v2/${id}`), member = shop.collection('membros').doc(user.uid), cat = db.doc(`catalogos_publicos_v2/${id}`);
    await shop.set({ nome: 'Loja de teste V2', slug: id, ativo: true, configVersao: 0, modulos: { cardapio: true } });
    await member.set({ tipo: 'usuario', papel: 'gerente', ativo: true });
    await db.doc(`rotas_publicas_v2/${id}`).set({ lojaId: id });
    await cat.set({ publicado: false, publicacaoManual: true, produtos: [{ id: 'burger', nome: 'Burger da casa', categoria: 'Hambúrgueres', descricao: 'Preparado na hora', precoCentavos: 2990, ativo: true, esgotado: false, grupos: [] }] });
    await win.loadURL('http://127.0.0.1:53700/gestao-v2');
    await wait('!!document.querySelector("#g-login")');
    await fill('[name=email]', email); await fill('[name=password]', password); await submit('#g-login');
    await wait('!!document.querySelector("#g-store")'); await fill('[name=loja]', id); await submit('#g-store');
    await wait('!!document.querySelector(".g-product")');
    await shot(1440); await shot(390);
    await js('document.querySelector(".g-product").click()');
    assert.equal(await js('window.dispatchEvent(new Event("beforeunload",{cancelable:true}))'), true);
    await fill('[name=nome]', 'Burger atualizado'); await fill('[name=preco]', '32.50'); await submit('.g-edit');
    await wait('document.querySelector("#g-status").textContent.includes("Produto salvo")');
    assert.equal((await cat.get()).data().produtos[0].precoCentavos, 3250);
    assert.equal((await cat.get()).data().publicado, false);
    assert.equal(await js('window.dispatchEvent(new Event("beforeunload",{cancelable:true}))'), true);
    assert.equal(await js('document.querySelector("#g-status").dataset.tone'), 'success');
    await js('document.querySelector("[data-section=loja]").click()');
    await fill('[name=segmento]', 'restaurante');
    assert.equal(await js('window.dispatchEvent(new Event("beforeunload",{cancelable:true}))'), false);
    await js('window.testOriginalConfirm=window.confirm;window.confirm=()=>false;document.querySelector("#g-sair").click();window.confirm=window.testOriginalConfirm;void 0');
    assert.equal(await js('document.querySelector("[name=segmento]").value'), 'restaurante');
    await js('document.querySelector("[name=retirada]").click()');
    await js('document.querySelector("[data-section=catalogo]").click();document.querySelector("[data-section=loja]").click()');
    assert.equal(await js('document.querySelector("[name=segmento]").value'), 'restaurante');
    assert.equal(await js('window.scrollY'), 0);
    await submit('.g-shop');
    await wait('document.querySelector("#g-status").textContent.includes("Configuração da loja atualizada")');
    assert.equal((await shop.get()).data().segmento, 'restaurante');
    assert.equal((await shop.get()).data().modulos.retirada, true);
    assert.equal((await cat.get()).data().publicado, false);
    assert.equal((await shop.get()).data().cozinha.papelMm, 80);
    await shot(1440); await shot(390);
    await js('document.querySelector("[data-section=delivery]").click()');
    await js('document.querySelector("[name=deliveryAtivo]").click()'); await submit('.g-delivery');
    await wait('document.querySelector(".g-delivery .g-result").textContent.includes("Adicione uma região")');
    await js('document.querySelector("#g-add-region").click()');
    await fill('[name=regiaoNome]', 'Região de teste'); await fill('[name=cepInicial]', '01000-000'); await fill('[name=cepFinal]', '01099-999');
    await fill('[name=taxa]', '7.50'); await fill('[name=prazo]', '40'); await fill('[name=minimo]', '25.00');
    await js('document.querySelector("[data-section=loja]").click();document.querySelector("[data-section=delivery]").click()');
    assert.equal(await js('document.querySelector("[name=taxa]").value'), '7.50');
    await js('document.querySelector("#g-add-region").click()');
    await fill('.g-region:last-child [name=regiaoNome]', 'Sobreposição'); await fill('.g-region:last-child [name=cepInicial]', '01050-000'); await fill('.g-region:last-child [name=cepFinal]', '01100-000');
    await submit('.g-delivery'); await wait('document.querySelector(".g-delivery .g-result").textContent.includes("sobrepor")');
    await js('document.querySelector(".g-region:last-child .g-remove-region").click()');
    await js('document.querySelector("[name=horariosAtivos]").click()');
    await submit('.g-delivery'); await wait('document.querySelector(".g-delivery .g-result").textContent.includes("pelo menos um período")');
    await js('document.querySelector("#g-add-period").click()');
    await fill('[name=inicio]', '18:00'); await fill('[name=fim]', '02:00');
    await submit('.g-delivery'); await wait('document.querySelector(".g-delivery .g-result").textContent.includes("depois da abertura")');
    await fill('[name=fim]', '24:00');
    await js('document.querySelector("#g-add-period").click()');
    await fill('.g-period:last-child [name=inicio]', '19:00'); await fill('.g-period:last-child [name=fim]', '20:00');
    await submit('.g-delivery'); await wait('document.querySelector(".g-delivery .g-result").textContent.includes("sobrepostos")');
    await fill('.g-period:last-child [name=dia]', '2'); await fill('.g-period:last-child [name=inicio]', '00:00'); await fill('.g-period:last-child [name=fim]', '02:00');
    await js('document.querySelector("[data-section=loja]").click();document.querySelector("[data-section=delivery]").click()');
    assert.equal(await js('document.querySelector("[name=fim]").value'), '24:00');
    await submit('.g-delivery'); await wait('document.querySelector("#g-status").textContent.includes("Delivery salvo")');
    const delivery = (await shop.get()).data().delivery;
    assert.deepEqual(delivery.horarios, { fuso: 'America/Sao_Paulo', periodos: [{ dia: 1, inicio: 1080, fim: 1440 }, { dia: 2, inicio: 0, fim: 120 }] });
    await shot(1440, true); await shot(390, true);
    await js('document.querySelector("[name=horariosAtivos]").click()'); await submit('.g-delivery');
    await wait('!document.querySelector("[name=horariosAtivos]").checked && !document.querySelector(".g-delivery button[type=submit]").disabled');
    assert.equal((await shop.get()).data().delivery.horarios, undefined);
    assert.equal(delivery.ativo, true); assert.equal(delivery.pedidoMinimoCentavos, 2500); assert.equal(delivery.regioes[0].taxaCentavos, 750); assert.equal(delivery.regioes[0].cepInicial, '01000000');
    assert.equal((await cat.get()).data().canais.delivery, true); assert.equal((await cat.get()).data().publicado, false);
    await shot(1440); await shot(390);
    await fill('[name=taxa]', '9.00'); await shop.update({ configVersao: 6 }); await submit('.g-delivery');
    await wait('document.querySelector(".g-delivery .g-result").textContent.includes("configuração mudou")');
    assert.equal(await js('document.querySelector("[name=taxa]").value'), '9.00');
    assert.equal((await shop.get()).data().delivery.regioes[0].taxaCentavos, 750);
    await win.reload(); await wait('!!document.querySelector("#g-store")'); await fill('[name=loja]', id); await submit('#g-store'); await wait('!!document.querySelector(".g-product")');
    await js('document.querySelector("[data-section=loja]").click()');
    await fill('[name=segmento]', 'padaria');
    await shop.update({ configVersao: 7 }); await submit('.g-shop');
    await wait('document.querySelector(".g-shop .g-result").textContent.includes("Recarregue")');
    assert.equal(await js('document.querySelector("[name=segmento]").value'), 'padaria');
    assert.equal((await shop.get()).data().segmento, 'restaurante');
    await win.reload(); await wait('!!document.querySelector("#g-store")'); await fill('[name=loja]', id); await submit('#g-store');
    await wait('!!document.querySelector(".g-product")');
    await js('document.querySelector(".g-product").click()'); await fill('[name=nome]', 'Rascunho preservado');
    await shop.update({ configVersao: 9 }); await submit('.g-edit');
    await wait('document.querySelector(".g-edit .g-result").textContent.includes("outra sessão")');
    assert.equal(await js('document.querySelector("[name=nome]").value'), 'Rascunho preservado');
    assert.equal(await js('document.querySelector(".g-edit button").disabled'), true);
    assert.equal((await cat.get()).data().produtos[0].nome, 'Burger atualizado');
    const reopen = async () => {
      await win.reload(); await wait('!!document.querySelector("#g-store")'); await fill('[name=loja]', id); await submit('#g-store'); await wait('!!document.querySelector(".g-product")');
      await js('document.querySelector("[data-section=mesas]").click()');
    };
    await reopen(); await js('document.querySelector("#g-new-table").click()');
    await fill('[name=mesaNome]', 'Mesa da varanda'); await fill('[name=mesaNumero]', '12');
    await js('document.querySelector("[data-section=loja]").click();document.querySelector("[data-section=mesas]").click()');
    assert.equal(await js('document.querySelector("[name=mesaNome]").value'), 'Mesa da varanda');
    await submit('.g-table-form'); await wait('document.querySelector("#g-status").textContent.includes("Mesa salva")');
    const tables = await shop.collection('mesas').get(), table = tables.docs[0];
    assert.equal(table.data().comandaPdvId, 'MESA-12');
    await js('document.querySelector(".g-show-qr").click()'); await wait('!!document.querySelector(".g-table-qr img")');
    assert.equal(await js('document.querySelector(".g-table-link").pathname'), `/v2/${id}/mesa/${table.id}`);
    assert.match(await js('document.querySelector(".g-table-qr img").src'), /^data:image\/png;base64,/);
    await shot(1440); await shot(390);
    await js('document.querySelector("#g-new-table").click()'); await fill('[name=mesaNome]', 'Outra mesa'); await fill('[name=mesaNumero]', '12');
    await submit('.g-table-form'); await wait('document.querySelector(".g-table-form .g-result").textContent.includes("já está vinculada")');
    assert.equal((await shop.collection('mesas').get()).size, 1);
    await reopen(); await table.ref.update({ atendimentoId: 'conta-local-aberta' });
    await js('document.querySelector(".g-edit-table").click();document.querySelector("[name=mesaAtiva]").click()');
    await submit('.g-table-form'); await wait('document.querySelector(".g-table-form .g-result").textContent.includes("Encerre a conta")');
    assert.equal((await table.ref.get()).data().ativo, true);
    await table.ref.update({ atendimentoId: null }); await reopen();
    await js('document.querySelector(".g-edit-table").click();document.querySelector("[name=mesaAtiva]").click()');
    await submit('.g-table-form'); await wait('document.querySelector("#g-status").textContent.includes("Mesa salva")');
    assert.equal((await table.ref.get()).data().ativo, false);
    assert.equal(await js('document.querySelectorAll(".g-show-qr").length'), 0);
    const batch = db.batch();
    for (let i = 0; i < 201; i++) batch.set(shop.collection('mesas').doc('page-' + String(i).padStart(3, '0')), { nome: 'Mesa de paginação ' + i, ativo: false, comandaPdvId: 'MESA-' + (100 + i) });
    await batch.commit(); await reopen();
    assert.equal(await js('document.querySelectorAll(".g-table-row").length'), 202);
    await js('document.querySelector("[data-section=pedidos]").click()');
    await wait('document.querySelector(".g-orders-status").textContent.includes("Nenhum pedido")');
    const ordersBatch = db.batch(), configBeforeOrders = (await shop.get()).data().configVersao;
    for (let i = 0; i < 26; i++) ordersBatch.set(shop.collection('pedidos').doc('order-' + String(i).padStart(2, '0')), { tipo: i % 2 ? 'delivery' : 'mesa', mesaNome: i % 2 ? '' : 'Mesa da varanda', status: i % 2 ? 'em_preparo' : 'novo', pagamento: 'pendente', recebidoPdv: Boolean(i % 2), criadoEm: admin.firestore.Timestamp.fromMillis(1700000000000 + i * 1000), totalCentavos: 3250, token: 'SEGREDO-NAO-EXIBIR', itens: [{ nome: 'Burger atualizado', quantidade: 1, totalCentavos: 3250 }] });
    await ordersBatch.commit();
    await js('document.querySelector(".g-orders-refresh").click()'); await wait('document.querySelectorAll(".g-order").length===25');
    assert.equal(await js('document.querySelector(".g-order").dataset.id'), 'order-25');
    await js('document.querySelector(".g-orders-more").click()'); await wait('document.querySelectorAll(".g-order").length===26');
    assert.equal(await js('document.querySelector(".g-orders-more").hidden'), true);
    assert.equal(await js('document.querySelector("#g-panel-pedidos").textContent.includes("SEGREDO-NAO-EXIBIR")'), false);
    assert.equal((await shop.get()).data().configVersao, configBeforeOrders);
    await js('document.querySelector(".g-order details").open=true'); await shot(1440); await shot(390);
    const foreign = await js(`(async()=>{const {ambienteGestaoV2}=await import('/src/lib/gestao-v2.js');try{await (await ambienteGestaoV2()).call('listarPedidosGestaoV2',{lojaId:'loja-sem-vinculo'});return 'allowed'}catch(e){return e.code}})()`);
    assert.equal(foreign, 'functions/permission-denied');
    await js('document.querySelector("[data-section=catalogo]").click();document.querySelector("#g-new-product").click()');
    await fill('[name=nome]', 'Batata da casa'); await fill('[name=preco]', '15.90'); await submit('.g-edit');
    await wait('document.querySelector("#g-status").textContent.includes("Produto salvo")');
    const created = (await cat.get()).data().produtos.find(p => p.nome === 'Batata da casa');
    assert.equal(created.precoCentavos, 1590); assert.equal((await cat.get()).data().produtos.length, 2);
    await js('document.querySelector("[data-section=adicionais]").click()');
    const chooseAddonProduct = async () => { await fill('#g-addon-product', created.id); await js('document.querySelector("#g-addon-product").dispatchEvent(new Event("change"))'); };
    await chooseAddonProduct(); await js('document.querySelector("#g-new-addon").click()');
    await fill('[name=nomeGrupo]', 'Complementos'); await fill('[name=opcaoNome]', 'Cheddar'); await fill('[name=opcaoPreco]', '3.50');
    await fill('[name=min]', '2'); await fill('[name=max]', '1'); await submit('.g-addon-form');
    await wait('document.querySelector(".g-addon-form .g-result").textContent.includes("mínimo")');
    await fill('[name=min]', '0');
    await js('document.querySelector("[data-section=loja]").click();document.querySelector("[data-section=adicionais]").click()');
    assert.equal(await js('document.querySelector("[name=opcaoNome]").value'), 'Cheddar');
    await submit('.g-addon-form'); await wait('document.querySelector("#g-status").textContent.includes("Adicional salvo")');
    let additionalProduct = (await cat.get()).data().produtos.find(p => p.id === created.id);
    assert.equal(additionalProduct.grupos[0].opcoes[0].precoCentavos, 350);
    await chooseAddonProduct(); await js('document.querySelector("#g-new-addon").click()');
    await fill('[name=grupo]', additionalProduct.grupos[0].id); await js('document.querySelector("[name=grupo]").dispatchEvent(new Event("change"))');
    await fill('[name=opcaoNome]', 'Bacon'); await fill('[name=opcaoPreco]', '4.00'); await submit('.g-addon-form');
    await wait('!document.querySelector(".g-addon-form")');
    additionalProduct = (await cat.get()).data().produtos.find(p => p.id === created.id);
    assert.equal(additionalProduct.grupos.length, 1); assert.equal(additionalProduct.grupos[0].opcoes.length, 2);
    await chooseAddonProduct(); await js('document.querySelector(".g-addon-list button").click();document.querySelector("[name=opcaoAtiva]").click()');
    await shot(1440); await shot(390); await submit('.g-addon-form'); await wait('!document.querySelector(".g-addon-form")');
    assert.equal((await cat.get()).data().produtos.find(p => p.id === created.id).grupos[0].opcoes[0].ativo, false);
    assert.equal((await cat.get()).data().publicado, false);
    await chooseAddonProduct(); await js('document.querySelector(".g-addon-list button").click()'); await fill('[name=opcaoNome]', 'Rascunho adicional');
    await shop.update({ configVersao: admin.firestore.FieldValue.increment(1) }); await submit('.g-addon-form');
    await wait('document.querySelector(".g-addon-form .g-result").textContent.includes("configuração mudou")');
    assert.equal(await js('document.querySelector("[name=opcaoNome]").value'), 'Rascunho adicional');
    await reopen(); await js('document.querySelector("[data-section=catalogo]").click();document.querySelector(".g-products .g-product").click()');
    await fill('[name=imagemUrl]', 'https://example.test/foto.jpg'); await submit('.g-edit');
    await wait('document.querySelector(".g-edit .g-result").textContent.includes("Cloudinary")');
    const photoUrl = 'https://res.cloudinary.com/flowpdv-teste/image/upload/produto-local.png';
    await fill('[name=imagemUrl]', photoUrl); await submit('.g-edit');
    await wait('document.querySelector("#g-status").textContent.includes("Produto salvo")');
    assert.equal((await cat.get()).data().produtos[0].imagemUrl, photoUrl);
    await js('document.querySelector(".g-products .g-product").click();document.querySelector(".g-photo-remove").click()');
    assert.equal(await js('document.querySelector("[name=imagemUrl]").value'), '');
    assert.equal((await cat.get()).data().produtos[0].imagemUrl, photoUrl);
    await submit('.g-edit'); await wait('!document.querySelector(".g-edit")');
    assert.equal((await cat.get()).data().produtos[0].imagemUrl, '');
    await js('document.querySelector("[data-section=contato]").click()');
    await fill('[name=contatoTelefone]', '123'); await submit('.g-contact-form');
    await wait('document.querySelector(".g-contact-form .g-result").textContent.includes("DDD")');
    await fill('[name=contatoTelefone]', '(11) 90000-0000'); await fill('[name=contatoEndereco]', 'Endereço comercial de teste');
    await submit('.g-contact-form'); await wait('document.querySelector("#g-status").textContent.includes("Contato salvo")');
    assert.deepEqual((await shop.get()).data().contato, { telefone: '11900000000', endereco: 'Endereço comercial de teste' });
    assert.deepEqual((await cat.get()).data().contato, (await shop.get()).data().contato);
    assert.equal((await cat.get()).data().publicado, false);
    await shot(1440); await shot(390);
    await fill('[name=contatoEndereco]', 'Rascunho de contato'); await shop.update({ configVersao: admin.firestore.FieldValue.increment(1) }); await submit('.g-contact-form');
    await wait('document.querySelector(".g-contact-form .g-result").textContent.includes("configuração mudou")');
    assert.equal(await js('document.querySelector("[name=contatoEndereco]").value'), 'Rascunho de contato');
    await reopen(); await js('document.querySelector("[data-section=contato]").click()');
    await fill('[name=contatoTelefone]', ''); await fill('[name=contatoEndereco]', ''); await submit('.g-contact-form');
    await wait('document.querySelector("#g-status").textContent.includes("Contato salvo")');
    assert.deepEqual((await cat.get()).data().contato, { telefone: '', endereco: '' });
    await js('document.querySelector("[data-section=pedidos]").click()'); await wait('document.querySelectorAll(".g-order").length===25');
    await member.update({ ativo: false });
    await js('document.querySelector(".g-orders-refresh").click()'); await wait('document.querySelector(".g-orders-status").textContent.includes("não está autorizado")');
    assert.equal(await js('document.querySelectorAll(".g-order").length'), 0);
    await win.reload(); await wait('!!document.querySelector("#g-store")'); await fill('[name=loja]', id); await submit('#g-store');
    await wait('document.querySelector("#g-status").textContent.includes("não tem permissão")');
    assert.equal(await js('document.querySelectorAll(".g-product").length'), 0);
    console.log('GESTAO V2 PASS: orders empty/26-row pagination/newest first/read-only/cross-store and revoked denial; tables/catalog/store/delivery/schedules regression; 1440/390.');
  } catch (e) { console.error(e); process.exitCode = 1; }
  finally {
    if (user) await admin.auth().deleteUser(user.uid);
    await db.recursiveDelete(db.doc(`lojas_v2/${id}`));
    await db.doc(`catalogos_publicos_v2/${id}`).delete(); await db.doc(`rotas_publicas_v2/${id}`).delete();
    win.destroy(); app.exit(process.exitCode || 0);
  }
});
