const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),{spawn}=require('child_process'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),pdv=path.resolve(repo,'../flowpdv-sistema/adega-pdv-gestao');
const out=path.resolve(pdv,process.env.PAINEL_ETAPA17?'../output/painel-abas17':'../output/painel-cardapio16');fs.mkdirSync(out,{recursive:true});
if(process.env.PAINEL_BROWSER){
 const {app,BrowserWindow}=require('electron');
 app.whenReady().then(async()=>{const win=new BrowserWindow({show:false,width:1366,height:900,webPreferences:{contextIsolation:true}});const js=s=>win.webContents.executeJavaScript(s);const wait=async s=>{const end=Date.now()+12000;while(Date.now()<end){if(await js(s))return;await new Promise(r=>setTimeout(r,50));}throw Error('Espera: '+s);};
 try{await win.loadURL(process.env.PAINEL_BROWSER);await wait('document.querySelectorAll(".prod-card").length===4');
 for(const width of [1366,390]){win.setContentSize(width,900);await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');win.webContents.invalidate();await new Promise(r=>setTimeout(r,120));fs.writeFileSync(path.join(out,(process.env.PAINEL_BEFORE?'antes':'depois')+'-'+width+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());if(!process.env.PAINEL_BEFORE)assert.equal(await js('document.documentElement.scrollWidth<=innerWidth'),true);}
 if(process.env.PAINEL_ETAPA17){await require('./painel-abas.cjs')({js,wait,win,out,before:!!process.env.PAINEL_BEFORE});} else if(!process.env.PAINEL_BEFORE){await js("document.querySelector('.prod-card').scrollIntoView({block:'start'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");win.webContents.invalidate();await new Promise(r=>setTimeout(r,120));fs.writeFileSync(path.join(out,'produto-mobile.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());await require('./painel-fluxo.cjs')({js,wait});}
 console.log('PAINEL UI PASS');app.exit(0);}catch(e){console.error(e);app.exit(1);}});
}else{(async()=>{
 const esbuild=require(path.join(pdv,'node_modules/esbuild')),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'flowpdv-painel-'));
 const mocks={
 'auth.js':`export const nomeDaLoja=l=>l.nome;export const sairDaLoja=async()=>{};`,
 'backup.js':`export const carregarBackupLoja=async()=>({produtos:window.fixture.produtos});export const precoProduto=p=>p.preco;export const produtoAtivo=()=>true;`,
 'overlay.js':`export const listarOverlays=async()=>{if(window.fixture.failLoad)throw Error('Conexão interrompida');return structuredClone(window.fixture.overlays)};export const lerConfig=async()=>structuredClone(window.fixture.config||{});export const salvarOverlay=async(c,id,p)=>{await new Promise(r=>setTimeout(r,60));if(window.fixture.failSave)throw Error('Falha simulada ao salvar');window.fixture.overlays[id]={...window.fixture.overlays[id],...p};};export const publicarCardapio=async()=>{window.fixture.publicacoes++};export const salvarConfig=async(c,p)=>{await new Promise(r=>setTimeout(r,80));if(window.fixture.failConfig)throw Error('Conexão interrompida');window.fixture.config={...window.fixture.config,...p};};export const assinarUpload=async()=>{};export const enviarFotoCloudinary=async()=>({});export const removerFoto=async()=>{};`,
 'pedidos.js':`export const atualizarStatusPedido=async(c,id,st)=>{window.fixture.statusCalls=(window.fixture.statusCalls||0)+1;await new Promise(r=>setTimeout(r,100));if(window.fixture.failStatus)throw Error('Falha ao atualizar pedido');window.fixture.pedidos.find(p=>p.id===id).status=st;};export const escutarPedidosLoja=(c,data,error)=>{window.fixture.emitPedidos=()=>data(structuredClone(window.fixture.pedidos||[]));window.fixture.erroPedidos=error;const t=setTimeout(window.fixture.emitPedidos,20);return()=>clearTimeout(t);};export const invalidarCardapioPublico=()=>{};`
 };
 const result=await esbuild.build({stdin:{contents:`import {renderPainel} from './src/pages/painel.js';window.fixture={publicacoes:0,produtos:[{id:'1',nome:'Hambúrguer da casa com queijo artesanal',categoria:'Lanches',preco:29.9},{id:'2',nome:'Batata rústica com alecrim',categoria:'Porções',preco:18},{id:'3',nome:'Suco natural de laranja',categoria:'Bebidas',preco:9.5},{id:'4',nome:'Água mineral',categoria:'Bebidas',preco:5}],overlays:{'1':{visivel:true,descricao:'Pão macio, carne na brasa e queijo artesanal.'},'2':{visivel:true,esgotado:true},'3':{visivel:true},'4':{visivel:false}}};window.recarregar=()=>renderPainel(document.querySelector('#app'),{chave:'LOJA-TESTE',licenca:{nome:'Casa do Mercado'}});await window.recarregar();`,resolveDir:repo},bundle:true,format:'esm',outfile:path.join(tmp,'fixture.js'),write:false,plugins:[{name:'fixture',setup(build){build.onResolve({filter:/\/lib\/(auth|backup|overlay|pedidos)\.js$/},a=>({path:path.basename(a.path),namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:mocks[a.path]}));}}]});
 const js=result.outputFiles.find(f=>!f.path.endsWith('.css')).text,css=result.outputFiles.find(f=>f.path.endsWith('.css'))?.text||'';
 const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/extra.css"><div id="app"></div><script type="module" src="/fixture.js"></script>');}else if(req.url==='/fixture.js'){res.setHeader('Content-Type','text/javascript');res.end(js);}else if(req.url==='/extra.css'){res.setHeader('Content-Type','text/css');res.end(css);}else{const f=req.url==='/styles.css'?path.join(repo,'src/styles.css'):path.join(repo,'public',req.url);if(fs.existsSync(f)){if(f.endsWith('.css'))res.setHeader('Content-Type','text/css');res.end(fs.readFileSync(f));}else{res.statusCode=404;res.end();}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const env={...process.env,PAINEL_BROWSER:'http://127.0.0.1:'+server.address().port};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(require(path.join(pdv,'node_modules/electron')),[__filename],{stdio:'inherit',env});child.on('exit',code=>{server.close();process.exitCode=code;});
})().catch(e=>{console.error(e);process.exitCode=1;});}
